{
 "title": "Gosbench",
 "tags": [ "overview" ],
 "time": { "from": "2020-06-15T18:58:39.079Z", "to": "2020-06-15T19:00:05.381Z" },
 "templating": {
  "list": [
   {
    "name": "osd_servers",
    "label": "OSD Host Name",
    "query": "label_values(ceph_disk_occupation,instance)"
   },
   { "name": "device_id", "label": "Disk Name", "query": "ceph_disk_occupation" },
   { "name": "max_devices", "query": "60" }
  ]
 },
 "panels": [
  { "title": "Gosbench native", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "S3 operation operations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (method,testName) (irate(gosbench_finished_ops[2s]))",
     "legendFormat": "{{ testName }} {{ method }}"
    },
    {
     "expr": "sum by (testName) (irate(gosbench_finished_ops[2s]))",
     "legendFormat": "SUM {{testName}}"
    }
   ]
  },
  {
   "title": "S3 latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gosbench_ops_latency_sum[2s]))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "95% S3 latency quantile",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(gosbench_ops_latency_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "S3 upload/download bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gosbench_uploaded_bytes[2s])) by (instance)",
     "legendFormat": "sent {{ instance}}"
    },
    {
     "expr": "sum(irate(gosbench_downloaded_bytes[2s])) by (instance)",
     "legendFormat": "received {{ instance}}"
    },
    {
     "expr": "abs(sum by (testName) (irate(gosbench_uploaded_bytes[2s]))) + abs(sum by (testName ) (irate(gosbench_downloaded_bytes[2s])))",
     "legendFormat": "SUM {{testName}}"
    }
   ]
  },
  {
   "title": "'$osd_servers' Performance Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$osd_servers Disk utilisation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "%Util" }
     ],
     "targets": [
      {
       "expr": "max by (device) (\nirate(node_disk_io_time_ms[5m]) and on (instance,device) ceph_disk_occupation{instance=~\"($osd_servers).*\",device=~\"($device_id)\"}\n) / 10",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "$osd_servers Disk IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "IOPS" }
     ],
     "targets": [
      {
       "expr": "max by (device) ((\nirate(node_disk_reads_completed{device=~\"($device_id)\",instance=~\"($osd_servers).*\"}[5m]) +\nirate(node_disk_writes_completed{device=~\"($device_id)\",instance=~\"($osd_servers).*\"}[5m])\n) and on (instance,device) ceph_disk_occupation{instance=~\"($osd_servers).*\",device=~\"($device_id)\"})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "$osd_servers Disk Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max by (device) ((\nirate(node_disk_write_time_ms{device=~ \"($device_id)\",instance=~\"($osd_servers).*\"}[5m])\n/\nclamp_min(irate(node_disk_writes_completed{device=~ \"($device_id)\",instance=~\"($osd_servers).*\"}[5m]),0.001)\n+\nirate(node_disk_read_time_ms{device=~ \"($device_id)\",instance=~\"($osd_servers).*\"}[5m])\n/\nclamp_min(irate(node_disk_reads_completed{device=~ \"($device_id)\",instance=~\"($osd_servers).*\"}[5m]),0.001)\n) and on (instance,device) ceph_disk_occupation{instance=~\"($osd_servers).*\",device=~\"($device_id)\"})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "$osd_servers Throughput by Disk",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max by (device) ((\nirate(node_disk_bytes_read{device=~\"($device_id)\",instance=~\"($osd_servers).*\"}[5m]) + \nirate(node_disk_bytes_written{device=~\"($device_id)\",instance=~\"($osd_servers).*\"}[5m])\n) and on (instance,device) ceph_disk_occupation{instance=~\"($osd_servers).*\",device=~\"($device_id)\"})",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "$osd_servers CPU Utilisation",
     "type": "graph",
     "description": "Shows the CPU breakdown. When multiple servers are selected,only the first host's cpu data is shown",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (\nirate(node_cpu{instance=~\"($osd_servers).*\",mode=~\"(irq|nice|softirq|steal|system|user|iowait)\"}[5m])\n) / scalar(\nsum(irate(node_cpu{instance=~\"($osd_servers).*\"}[5m]))\n) * 100",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Loadgen CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (avg by (instance,mode) (rate(node_cpu{instance=~\"rhload.*\",mode!=\"idle\"}[5m])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "$osd_servers Network Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum by (device) (irate(node_network_receive_bytes{instance=~\"($osd_servers).*\",device=~\"(eth|en|bond|ib|mlx|p).*\"}[5m]))",
       "legendFormat": "{{device}}.rx"
      },
      {
       "expr": "sum by (device) (irate(node_network_transmit_bytes{instance=~\"($osd_servers).*\",device=~\"(eth|en|bond|ib|mlx|p).*\"}[5m]))",
       "legendFormat": "{{device}}.tx"
      }
     ]
    }
   ]
  },
  { "title": "Gosbench", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "op count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 25 },
   "format": "locale",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(gosbench_opencensus_io_http_client_completed_count)"
    }
   ]
  },
  {
   "title": "byte count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 25 },
   "format": "bytes",
   "valueName": "delta",
   "targets": [
    {
     "expr": "abs(sum(gosbench_opencensus_io_http_client_received_bytes_sum))+abs(sum(gosbench_opencensus_io_http_client_sent_bytes_sum))"
    }
   ]
  },
  {
   "title": "Operations per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gosbench_opencensus_io_http_client_completed_count[2s])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(gosbench_opencensus_io_http_client_completed_count[2s]))",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "Gosbench sent/received bytes sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gosbench_opencensus_io_http_client_sent_bytes_sum{}[2s])) by (instance)",
     "legendFormat": "sent {{ instance}}"
    },
    {
     "expr": "sum(irate(gosbench_opencensus_io_http_client_received_bytes_sum{}[2s])) by (instance)",
     "legendFormat": "received {{ instance}}"
    },
    {
     "expr": "abs(sum(irate(gosbench_opencensus_io_http_client_sent_bytes_sum{}[2s]))) + abs(sum(irate(gosbench_opencensus_io_http_client_received_bytes_sum{}[2s])))",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gosbench_opencensus_io_http_client_roundtrip_latency_sum[2s]))",
     "legendFormat": "latency"
    }
   ]
  }
 ]
}